<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\ArticleController::createOrUpdate' => function () {
    return ($this->privates['.service_locator.pkmKmiv'] ?? $this->load('get_ServiceLocator_PkmKmivService.php'));
}, 'App\\Controller\\ArticleController::index' => function () {
    return ($this->privates['.service_locator.rbz6q7p'] ?? $this->load('get_ServiceLocator_Rbz6q7pService.php'));
}, 'App\\Controller\\ArticleController::show' => function () {
    return ($this->privates['.service_locator.SS3N0Sl'] ?? $this->load('get_ServiceLocator_SS3N0SlService.php'));
}, 'App\\Controller\\SecurityController::registration' => function () {
    return ($this->privates['.service_locator.hBT203u'] ?? $this->load('get_ServiceLocator_HBT203uService.php'));
}, 'App\\Controller\\ArticleController:createOrUpdate' => function () {
    return ($this->privates['.service_locator.pkmKmiv'] ?? $this->load('get_ServiceLocator_PkmKmivService.php'));
}, 'App\\Controller\\ArticleController:index' => function () {
    return ($this->privates['.service_locator.rbz6q7p'] ?? $this->load('get_ServiceLocator_Rbz6q7pService.php'));
}, 'App\\Controller\\ArticleController:show' => function () {
    return ($this->privates['.service_locator.SS3N0Sl'] ?? $this->load('get_ServiceLocator_SS3N0SlService.php'));
}, 'App\\Controller\\SecurityController:registration' => function () {
    return ($this->privates['.service_locator.hBT203u'] ?? $this->load('get_ServiceLocator_HBT203uService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
