<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rbz6q7p' shared service.

return $this->privates['.service_locator.rbz6q7p'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('articleRepo' => function (): \App\Repository\ArticleRepository {
    return ($this->privates['App\Repository\ArticleRepository'] ?? $this->load('getArticleRepositoryService.php'));
}, 'quoteRepo' => function (): \App\Repository\QuoteRepository {
    return ($this->privates['App\Repository\QuoteRepository'] ?? $this->load('getQuoteRepositoryService.php'));
}, 'widgetRepo' => function (): \App\Repository\WidgetRepository {
    return ($this->privates['App\Repository\WidgetRepository'] ?? $this->load('getWidgetRepositoryService.php'));
}));
