<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0rIyvcP\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0rIyvcP/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0rIyvcP.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0rIyvcP\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container0rIyvcP\srcDevDebugProjectContainer(array(
    'container.build_hash' => '0rIyvcP',
    'container.build_id' => '6b9f0082',
    'container.build_time' => 1537822365,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0rIyvcP');
